### PR TITLE
Wiener distribution

### PR DESCRIPTION
**Pull request by randommm**
#### Summary:
Adds Wiener first time passage distribution. Fix issue #765.

#### Intended Effect:
Looking at the mailing list, it seems we have considerable demand for this distribution, so here we have it.

#### How to Verify:
Code check.

#### Side Effects:
I'm relying on auto differentiation here.

#### Documentation:
Included.

### CODE REVIEW

**Comment by syclik** [comment]
Jenkins, retest this please.

**Comment by mshvartsman** [comment]
I started going down the path of writing my own WFPT distribution before finding out that this exists. I'd like to help. I don't have push access to stan-dev, so I think the right thing should be to fork the repo and develop locally. 

So I did that. As a start, I just edited the file to make it pass cpplint, which looks like it was the latest CI failure. My copy lives in my fork here: https://github.com/mshvartsman/stan/blob/feature/issue-765-wiener-distribution/src/stan/math/prim/scal/prob/wiener_log.hpp

What's the right way to test locally and merge this in? I'm not sure how to interact with ongoing pull requests. Should I submit a pull request against @randommm's fork?

**Comment by randommm** [comment]
Hi, thanks very much for your contributions.

You could send a pull request against feature/issue-765-wiener-distribution (of stan-dev/stan remote), but this time it's not necessary since I've already added your commits.

**Comment by mshvartsman** [comment]
I believe that the latest failure is no longer on wiener_log.hpp: 
```
cpplint --output=vs7 --counting=detailed --root=src --exten
sion=hpp,cpp --filter=-runtime/indentation_namespace,-readability/namespace,-legal/copyright,-whitespace/indent,-runtime/reference src/stan/math/prim/scal/prob/wiener_log.hpp
Done processing src/stan/math/prim/scal/prob/wiener_log.hpp
Total errors found: 0
```

I also submitted a pull request for lint fixes on the unit tests file, looks like that just got merged. 

That said, the wiener unit tests fail to compile on my machine (OSX, gcc 4.9) -- but so do non-wiener tests:
```
python runTests.py src/test/prob/wiener
<...>
In file included from src/test/prob/utility.hpp:7:0,
                 from src/test/prob/test_fixture_distr.hpp:7,
                 from src/test/prob/wiener//wiener_00000_generated_fd_test.cpp:3:
src/stan/math/fwd/mat/fun/Eigen_NumTraits.hpp: At global scope:
src/stan/math/fwd/mat/fun/Eigen_NumTraits.hpp:15:10: error: partial specialization of ‘Eigen::NumTraits<stan::agrad::fvar<T> >’ after instantiation of ‘Eigen::NumTraits<stan::agrad::fvar<stan::agrad::var> >’ [-fpermissive]
   struct NumTraits<stan::agrad::fvar<T> > {
          ^
src/stan/math/fwd/mat/fun/Eigen_NumTraits.hpp:15:10: error: partial specialization of ‘Eigen::NumTraits<stan::agrad::fvar<T> >’ after instantiation of ‘Eigen::NumTraits<stan::agrad::fvar<stan::agrad::fvar<stan::agrad::var> > >’ [-fpermissive]
In file included from src/stan/math/rev/core/operator_unary_plus.hpp:7:0,
                 from src/stan/math/rev/core.hpp:35,
                 from src/test/prob/test_fixture_distr.hpp:4,
                 from src/test/prob/wiener//wiener_00000_generated_fd_test.cpp:3:
<...>
```

Seems to be a similar error to issue reported here https://groups.google.com/forum/#!msg/stan-dev/elDEK5P755U/iKra1XRWFwAJ, but I think that specific issue was fixed in #1363.

**Comment by syclik** [comment]
This looks like an include problem. I've got a bit on my plate this week,
but I'll try to get to it soon.

**Comment by mshvartsman** [comment]
Thanks. Seems to compile fine on clang-602.0.49 (current Yosemite default I think). Let me know if there is anything else I can do to help figure out the gcc 4.9 issue here. 

Waiting for test results locally now. I guess this will take a while. 

@randommm, did you have plans for the RNG? Port the Tuerlinckx et al. 2001 rejection sampling method from RWiener, or something else?

**Comment by randommm** [comment]
@mshvartsman sorry, I only saw your comment about the RNG now. No, it wasn't on my plans, but I'll take a look at the article as soon as time allows and maybe I'll implement it.

**Comment by syclik** [comment]
Marco, the last merged pull request will affect all the open pull requests
involving math. I'll go through and try to update them today.

**Comment by randommm** [comment]
The pull request for univariate sufficient normal has already passed. I think this one will pass too with the last fix: it passed the headers test in my computer.

I'm just curious, why some extra using statements like

      using std::log;

necessary now?

**Comment by syclik** [comment]
@randommm, sorry about the delay.

I think it happened because we've started to be more careful about the namespace. In the past when, when we used `log`, we used to pick up the `::log` from `<cmath>` or `<math.h>` and `stan::agrad::log` from `<stan/math/rev/prim/scal/fun/log.hpp>`. 

(now that I wrote that out, it doesn't feel so satisfying an answer; sorry -- I've got nothing better)

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 1]
```diff
@@ -0,0 +1,224 @@
...
+#include <stan/math/prim/scal/meta/return_type.hpp>
+#include <stan/math/prim/scal/meta/include_summand.hpp>
+#include <boost/math/distributions.hpp>
+#include <cmath>
+#include <algorithm>  // for max
+
+namespace stan {
+
+  namespace math {
+    /**
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: This code comment isn't attached to anything.

**Comment by bob-carpenter** [comment]
@syclik This one's heavily into the math lib.  Can you help merge it?

**Comment by syclik** [comment]
Yes.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 2]
```diff
@@ -0,0 +1,224 @@
...
+      check_finite(function, "Boundary separation", alpha);
+      check_finite(function, "A-priori bias", beta);
+      check_finite(function, "Nondecision time", tau);
+      check_finite(function, "Drift rate", delta);
+      check_positive(function, "Random variable", y);
+      check_positive(function, "Boundary separation", alpha);
+      check_positive(function, "Nondecision time", tau);
+      check_bounded(function, "A-priori bias", beta , 0, 1);
+      check_consistent_sizes(function,
+       "Random variable", y,
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Need to run int on some of this.  You need at least 4 space indent and ideally just line up under "function".

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 3]
```diff
@@ -0,0 +1,224 @@
...
+          kl = 1.0 / (MY_PI * sqrt(x));  // set to boundary condition
+        }
+        // calculate number of terms needed for small t:
+        // if error threshold is set low enough
+        if ((2.0 * sqrt(2.0 * MY_PI * x) * WIENER_ERR) < 1) {
+          // compute bound
+          ks = 2.0 + sqrt(-2.0 * x *
+               log(2.0 * sqrt(2.0 * MY_PI * x) * WIENER_ERR));
+          // ensure boundary conditions are met
+          ks = (ks > sqrt(x) + 1.0) ? ks : sqrt(x) + 1.0;
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: assign `sqrt(x) + 1` to local and reuse it rather than recomputing.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 4]
```diff
@@ -0,0 +1,224 @@
...
+
+
+        x = x - tau_vec[i];  // remove non-decision time from x
+        x = x / alpha2;  // convert t to normalized time tt
+
+        // calculate number of terms needed for large t:
+        // if error threshold is set low enough
+        if (MY_PI * x * WIENER_ERR < 1) {
+          // compute bound
+          kl = sqrt(-2.0 * log(MY_PI * x * WIENER_ERR) / (pow(MY_PI, 2) * x));
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Use `sqrt(MY_PI)` instead.  But overall, don't define a new global MY_PI --- just use the Boost one directly.  If you need new constants, add them to Stan math.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 5]
```diff
@@ -0,0 +1,224 @@
...
+
+      for (size_t i = 0; i < N; i++)
+        if (y_vec[i] < tau_vec[i]) {
+          lp = stan::math::negative_infinity();
+          return lp;
+        }
+
+        for (size_t i = 0; i < N; i++) {
+          typename scalar_type<T_beta>::type one_minus_beta = 1.0 - beta_vec[i];
+          typename scalar_type<T_alpha>::type alpha2 = alpha_vec[i] *
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Use `square()` instead of `a * a`

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 6]
```diff
@@ -0,0 +1,224 @@
...
+        x = x - tau_vec[i];  // remove non-decision time from x
+        x = x / alpha2;  // convert t to normalized time tt
+
+        // calculate number of terms needed for large t:
+        // if error threshold is set low enough
+        if (MY_PI * x * WIENER_ERR < 1) {
+          // compute bound
+          kl = sqrt(-2.0 * log(MY_PI * x * WIENER_ERR) / (pow(MY_PI, 2) * x));
+          // ensure boundary conditions met
+          kl = (kl > 1.0 / (MY_PI * sqrt(x))) ? kl : 1.0 / (MY_PI * sqrt(x));
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: calculate `sqrt(x)` and save it for reuse.   `sqrt()` is a very expensive function!

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 7]
```diff
@@ -0,0 +1,224 @@
...
+        } else {  // if error threshold set too high
+          kl = 1.0 / (MY_PI * sqrt(x));  // set to boundary condition
+        }
+        // calculate number of terms needed for small t:
+        // if error threshold is set low enough
+        if ((2.0 * sqrt(2.0 * MY_PI * x) * WIENER_ERR) < 1) {
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Don't dynamically redo the math.  Calculate sqrt(2 * PI) [I think we have it as a built in constant] and multiply that by `sqrt(x)`, which you've already saved and calculated at this point.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 8]
```diff
@@ -0,0 +1,224 @@
...
+               log(2.0 * sqrt(2.0 * MY_PI * x) * WIENER_ERR));
+          // ensure boundary conditions are met
+          ks = (ks > sqrt(x) + 1.0) ? ks : sqrt(x) + 1.0;
+        } else {  // if error threshold was set too high
+          ks = 2.0;  // minimal kappa for that case
+        }
+        // compute density: f(tt|0,1,w)
+        if (ks < kl) {  // if small t is better (i.e., lambda<0)
+          K = ceil(ks);  // round to smallest integer meeting error
+          for (k = -floor((K - 1.0) / 2.0); k <= ceil((K - 1.0) / 2.0); k++)
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Same thing --- don't do all this redundant calculation.  If there's a shared expression, set it to a local and reuse it.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 9]
```diff
@@ -0,0 +1,224 @@
...
+            // increment sum
+            tmp += (one_minus_beta + 2.0 * k) *
+                    exp(-(pow((one_minus_beta + 2.0 * k), 2)) / 2.0 / x);
+            // add constant term
+            tmp = log(tmp) - 0.5 * LOG_TWO - MY_LN_SQRT_PI - 1.5 * log(x);
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: At least bracket all of `0.5 * LOG_TWO - MY_LN_SQRT_PI` so it's evaluated as a double by itself.  You don't want to pollute potential non-constants in arithmetic.  Ideally, you'd just make it a constant.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 10]
```diff
@@ -0,0 +1,224 @@
...
+        } else {  // if large t is better...
+          K = ceil(kl);  // round to smallest integer meeting error
+          for (k = 1; k <= K; k++)
+            // increment sum
+            tmp += k * exp(-(pow(k, 2)) *
+                   (pow(MY_PI, 2)) * x / 2.0) *
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: always `square`, never `pow(,2)`.

Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Prefer `0.5 * x` over `x / 2` because multiplication is faster than division.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 11]
```diff
@@ -0,0 +1,224 @@
...
+            // increment sum
+            tmp += (one_minus_beta + 2.0 * k) *
+                    exp(-(pow((one_minus_beta + 2.0 * k), 2)) / 2.0 / x);
+            // add constant term
+            tmp = log(tmp) - 0.5 * LOG_TWO - MY_LN_SQRT_PI - 1.5 * log(x);
+        } else {  // if large t is better...
+          K = ceil(kl);  // round to smallest integer meeting error
+          for (k = 1; k <= K; k++)
+            // increment sum
+            tmp += k * exp(-(pow(k, 2)) *
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: If there are bits of this formula reused across loop iterations, save them outside the loop.

**Comment by bob-carpenter** [comment]
I made a million little comments on the way the math was formulated inline.  I'm OK with either:

1.  Making the efficiency updates and re-reviewing. 

2.  Go with the existing version and make it faster later.

**Comment by bob-carpenter** [comment]
Is there a reason `OperandsAndPartials` isn't used for this?

**Comment by randommm** [comment]
I hope I catched all your comments =]

Is OK to define, inside the file, constants that are clearly file specific like `WIENER_ERR`? There's a bunch of possible constants, but this would pollute too much the `constants.hpp` file.

I didn't use `OperandsAndPartials` because I have no idea on how to define the gradients analytically (I've used the author's original code).

**Comment by bob-carpenter** [comment]
> On Jun 20, 2015, at 10:00 AM, Marco Inacio <notifications@github.com> wrote:
> 
> I hope I catched all your comments =]
> 
> Is OK to define, inside the file, constants that are clearly file specific like WIENER_ERR? There's a bunch of possible constants, but this would pollute too much the constants.hpp file.

You can, but they wind up polluting the namespace anyway whenever
the file's brought in.  We don't really have a coding style for
this and we've thus been inconsistent.

If it's just for a function, make it a static variable in
that function rather than a constant in the namespace.  When
in doubt, narrower scope is better.  But it's probably better
to put it in the namespace with a very clear name if you need
to use it in multiple functions that aren't all in a class.  

> I didn't use OperandsAndPartials because I have no idea on how to define the gradients analytically (I've used the author's original code).

OK, that makes sense.  

- Bob

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 12]
```diff
@@ -0,0 +1,229 @@
...
+#include <stan/math/prim/scal/meta/include_summand.hpp>
+#include <boost/math/distributions.hpp>
+#include <cmath>
+#include <algorithm>  // for max
+
+namespace stan {
+
+  namespace math {
+
+     const double WIENER_ERR = 0.000001,
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: I'd strongly prefer to see two const double declarations here.  What'd cpplint say?

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 13]
```diff
@@ -0,0 +1,229 @@
...
+          return lp;
+        }
+
+      for (size_t i = 0; i < N; i++) {
+        typename scalar_type<T_beta>::type one_minus_beta
+          = 1.0 - beta_vec[i];
+        typename scalar_type<T_alpha>::type alpha2
+          = square(alpha_vec[i]);
+        T_return_type x = y_vec[i];
+        T_return_type kl, ks, tmp = 0;
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: This doesn't cause uninitialized viable errors for kl and ks?

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 14]
```diff
@@ -0,0 +1,229 @@
...
+        T_return_type sqrt_x = sqrt(x);
+
+        // calculate number of terms needed for large t:
+        // if error threshold is set low enough
+        if (pi() * x * WIENER_ERR < 1) {
+          // compute bound
+          kl = sqrt(-2.0 * log(pi() * x * WIENER_ERR) * SQRT_PI) /
+               sqrt_x;
+          // ensure boundary conditions met
+          kl = (kl > 1.0 / (pi() * sqrt_x)) ?
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: You really don't want to be computing (1 / pi() * sqrt_x) twice.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 15]
```diff
@@ -0,0 +1,229 @@
...
+          K = ceil(ks);  // round to smallest integer meeting error
+          T_return_type tmp_expr1 = (K - 1.0) / 2.0;
+          T_return_type tmp_expr2 = ceil(tmp_expr1);
+          for (k = -floor(tmp_expr1); k <= tmp_expr2; k++)
+            // increment sum
+            tmp += (one_minus_beta + 2.0 * k) *
+                    exp(-(square(one_minus_beta + 2.0 * k)) * 0.5 / x);
+            // add constant term
+            tmp = log(tmp) -
+                  LOG_TWO_OVER_TWO_PLUS_LOG_SQRT_PI- 1.5 * log(x);
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: spaces between operators like `-`, but cpplint will be telling you this --- you need to run `make cpplint` (and probably pipe it to a file, as in `make cpplint >& lint.txt`, because I think the messages come out on both stderr and stdout.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 16]
```diff
@@ -0,0 +1,229 @@
...
+            // increment sum
+            tmp += k * exp(-(pow(k, 2)) *
+                   (square(pi()) * 0.5 * x)) *
+                   sin(k * pi() * one_minus_beta);
+            tmp = log(tmp) + 2.0 * LOG_SQRT_PI;  // add constant term
+        }
+
+        // convert to f(t|v,a,w) and return result
+        lp += delta_vec[i] * alpha_vec[i] * one_minus_beta -
+              pow(delta_vec[i], 2) * x * alpha2 / 2.0 -
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: replace all `pow(a, 2)` with `square(a)`.  The power function is really expensive compared to mulitplying `a * a` for primities and `square(a)` is more efficient for derivatives (it skips a conditional in the definiiton of `pow()` which will delegate to `square()` if the second argument is a constant 2.

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp [hunk 17]
```diff
@@ -0,0 +1,229 @@
...
+    template <typename T_y, typename T_alpha, typename T_tau,
+              typename T_beta, typename T_delta>
+    inline
+    typename return_type<T_y, T_alpha, T_tau, T_beta, T_delta>::type
+    wiener_log(const T_y& y, const T_alpha& alpha, const T_tau& tau,
+               const T_beta& beta, const T_delta& delta) {
+      return wiener_log<false>(y, alpha, tau, beta, delta);
+    }
+
+    /* Not actually implemented yet
```
Comment (bob-carpenter) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: Don't include commented out code.   Either include it or don't.  You can start a new branch if you don't want to lose it.

**Comment by bob-carpenter** [comment]
I think this one's pretty close --- it'd be great to get it into 2.7.0.  There are a couple more efficiency issues, a removal of a commented-out section of code, and some lint testing.  The efficiency issues aren't critical, but if you have the lid off the implementation, you might as well do them now.  

Thanks for seeing this through!

**Comment by randommm** [comment]
I'll fix the remaining problems now. Why didn't Jenkins catch the cpplint errors?

File: lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp (hunk 13 above)
Comment (randommm) [inline lib/stan_math_2.6.3/stan/math/prim/scal/prob/wiener_log.hpp]: I doesn't seem to. Should I initialize all them with value 0?

**Comment by bob-carpenter** [comment]
The Jenkins job relies on Daniel updating the number of
errors expected in the job with every merge into develop, so
it's probably behind.

I keep trying to knock the lint down in every file I touch
for a pull request.  I think we're down to around 1300 or so
now, so there's still a long way to go (many in the parser).

- Bob

**Comment by randommm** [comment]
OK. Hopefully it's all fixed now. Also, at least for me cpplint is showing zero errors in all lib/math folder.
