### PR TITLE
Fix ambiguity with size_t on 32-bit platforms

### PR DESCRIPTION
**Pull request by andrjohns**
#### Submission Checklist

- [x] Run unit tests: `./runTests.py src/test/unit`
- [x] Run cpplint: `make cpplint`
- [x] Declare copyright holder and open-source license: see below

#### Summary

I'm seeing a compilation failure with some downstream packaging on 32-bit systems:

```
../inst/include/stan/callbacks/structured_writer.hpp:88:16: error: class member cannot be redeclared
   88 |   virtual void write(const std::string& key, unsigned int value) {}
      |                ^
../inst/include/stan/callbacks/structured_writer.hpp:72:16: note: previous definition is here
   72 |   virtual void write(const std::string& key, std::size_t value) {}
```

Which is because `std::size_t` is an `unsigned int` on 32 bit. This PR just changes the overloads to explicit sized-types

#### Intended Effect

Fix compilation on 32-bit

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company): Andrew Johnson

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Review by WardBrian — APPROVED** [review]

**Comment by WardBrian** [comment]
@andrjohns after updating to 2.40, which included this patch, I've started getting failures on my macos ci:

```
[7](https://github.com/WardBrian/tinystan/actions/runs/35233548032/job/105243549696?pr=110#step:5:218)
./stan/src/stan/services/pathfinder/single.hpp:733:25: error: call to member function 'write' is ambiguous
  733 |       diagnostic_writer.write("iter", lbfgs.iter_num());
      |       ~~~~~~~~~~~~~~~~~~^~~~~
src/tinystan.cpp:243:49: note: in instantiation of function template specialization 'stan::services::pathfinder::pathfinder_lbfgs_single<false, false, stan::model::model_base, stan::callbacks::structured_writer, tinystan::io::buffer_writer>' requested here
  243 |       return_code = stan::services::pathfinder::pathfinder_lbfgs_single(
      |                                                 ^
./stan/src/stan/callbacks/structured_writer.hpp:59:16: note: candidate function
   59 |   virtual void write(const std::string& key, bool value) {}
      |                ^
./stan/src/stan/callbacks/structured_writer.hpp:66:16: note: candidate function
   66 |   virtual void write(const std::string& key, int value) {}
      |                ^
./stan/src/stan/callbacks/structured_writer.hpp:73:16: note: candidate function
   73 |   virtual void write(const std::string& key, uint64_t value) {}
      |                ^
./stan/src/stan/callbacks/structured_writer.hpp:80:16: note: candidate function
   80 |   virtual void write(const std::string& key,
      |                ^
./stan/src/stan/callbacks/structured_writer.hpp:89:16: note: candidate function
   89 |   virtual void write(const std::string& key, uint32_t value) {}
      |                ^
./stan/src/stan/callbacks/structured_writer.hpp:96:16: note: candidate function
   96 |   virtual void write(const std::string& key, double value) {}
```

Which seem to be based around `size_t`, any clue?

**Comment by andrjohns** [comment]
> @andrjohns after updating to 2.40, which included this patch, I've started getting failures on my macos ci:
> 
> ```
> [7](https://github.com/WardBrian/tinystan/actions/runs/35233548032/job/105243549696?pr=110#step:5:218)
> ./stan/src/stan/services/pathfinder/single.hpp:733:25: error: call to member function 'write' is ambiguous
>   733 |       diagnostic_writer.write("iter", lbfgs.iter_num());
>       |       ~~~~~~~~~~~~~~~~~~^~~~~
> src/tinystan.cpp:243:49: note: in instantiation of function template specialization 'stan::services::pathfinder::pathfinder_lbfgs_single<false, false, stan::model::model_base, stan::callbacks::structured_writer, tinystan::io::buffer_writer>' requested here
>   243 |       return_code = stan::services::pathfinder::pathfinder_lbfgs_single(
>       |                                                 ^
> ./stan/src/stan/callbacks/structured_writer.hpp:59:16: note: candidate function
>    59 |   virtual void write(const std::string& key, bool value) {}
>       |                ^
> ./stan/src/stan/callbacks/structured_writer.hpp:66:16: note: candidate function
>    66 |   virtual void write(const std::string& key, int value) {}
>       |                ^
> ./stan/src/stan/callbacks/structured_writer.hpp:73:16: note: candidate function
>    73 |   virtual void write(const std::string& key, uint64_t value) {}
>       |                ^
> ./stan/src/stan/callbacks/structured_writer.hpp:80:16: note: candidate function
>    80 |   virtual void write(const std::string& key,
>       |                ^
> ./stan/src/stan/callbacks/structured_writer.hpp:89:16: note: candidate function
>    89 |   virtual void write(const std::string& key, uint32_t value) {}
>       |                ^
> ./stan/src/stan/callbacks/structured_writer.hpp:96:16: note: candidate function
>    96 |   virtual void write(const std::string& key, double value) {}
> ```
> 
> Which seem to be based around `size_t`, any clue?

Ahhh I love platform consistency:

Platform | std::size_t | uint64_t
-- | -- | --
64-bit Linux | unsigned long | unsigned long
64-bit macOS | unsigned long | unsigned long long

I'll update to just add all overloads (`unsigned long`, etc)
