### ISSUE TITLE
Stan is incompatible with Boost 1.62.0

### ISSUE THREAD

**Issue by bgoodri** [stan-dev/stan#2108]
#### Summary:

The stanc executable does not build with Boost 1.62.0

#### Description:

The stanc executable does not build with Boost 1.62.0

#### Reproducible Steps:

`R CMD INSTALL rstan_*.tar.gz`

after installing a BH based on 1.62.0

#### Current Output:

```
clang++-3.9 -I/usr/share/R/include -DNDEBUG -I"../inst/include" -I"../inst/include/boost_not_in_BH" -I"`"/usr/lib/R/bin/Rscript" --vanilla -e "cat(system.file('include', 'src', package = 'StanHeaders'))"`" -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -DFUSION_MAX_VECTOR_SIZE=12  -I"/usr/local/lib/R/site-library/Rcpp/include" -I"/usr/local/lib/R/site-library/RcppEigen/include" -I"/usr/local/lib/R/site-library/BH/include" -I"/usr/local/lib/R/site-library/StanHeaders/include"   -fpic  -O3 -march=native -mtune=native -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -Wno-ignored-attributes -Wno-deprecated-declarations  -c lang__ast_def.cpp -o lang__ast_def.o
In file included from lang__ast_def.cpp:18:
/usr/local/lib/R/site-library/StanHeaders/include/src/stan/lang/ast_def.cpp:760:30: error: no matching constructor for initialization of 'printable_t' (aka
      'variant<recursive_wrapper<basic_string<char> >, recursive_wrapper<stan::lang::expression> >')
    printable::printable() : printable_("") { }
                             ^          ~~
/usr/local/lib/R/site-library/BH/include/boost/variant/variant.hpp:1797:5: note: candidate constructor not viable: no known conversion from 'const char [1]' to 'const
      boost::variant<boost::recursive_wrapper<std::__cxx11::basic_string<char> >, boost::recursive_wrapper<stan::lang::expression>, boost::detail::variant::void_,
      boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,
      boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_,
      boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_>' for 1st argument
    variant(const variant& operand)
    ^
/usr/local/lib/R/site-library/BH/include/boost/variant/variant.hpp:1759:35: note: candidate template ignored: disabled by 'enable_if' [with T = char [1]]
        typename boost::enable_if<mpl::and_<
                                  ^
/usr/local/lib/R/site-library/BH/include/boost/variant/variant.hpp:1770:37: note: candidate template ignored: disabled by 'enable_if' [with T = char const[1]]
        , typename boost::enable_if<mpl::and_<
                                    ^
/usr/local/lib/R/site-library/BH/include/boost/variant/variant.hpp:1422:5: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    variant() 
    ^
1 error generated.
/usr/lib/R/etc/Makeconf:141: recipe for target 'lang__ast_def.o' failed
make: *** [lang__ast_def.o] Error 1
ERROR: compilation failed for package ‘rstan’
```

#### Expected Output:

A successful install

#### Additional Information:

Need to fix ASAP even if I have to put a workaround into rstan

#### Current Version:
v2.12.0

**Comment by syclik** [comment]
@bgoodri, when you say "ASAP," what do you mean? What caused this? Did R's `bh` change version? Will it no longer build now for `rstan`?

**Comment by bgoodri** [comment]
Yes

**Comment by bgoodri** [comment]
@bob-carpenter It compiles if I just change line 760 to
```
 printable::printable() : printable_(static_cast<std::string>("")) { }
```
Is that safe?

**Comment by bob-carpenter** [comment]
Yes, that should be fine.  But instead of

> printable_(static_cast<std::string>(""))


I'd suggest just

  printable_(std::string());

or even just

  printable_()

because the no-arg constructor produces the same result (zero length
std::string).

- Bob

**Comment by bob-carpenter** [comment]
fixed with pull request #2109
