### ISSUE TITLE
can't compile lkj_corr_cholesky_log in develop branch of cmdstan

### ISSUE THREAD

**Issue by rtrangucci** [stan-dev/stan#1337]
The following model doesn't compile in cmdstan currently:

```
data {
  int<lower=1> N; // number of total observations
  int<lower=1> G; // number of groups
  int<lower=1> K; // number of predictors
  int<lower=1,upper=G> group_id[N]; // group_id categorical variable 
  int<lower=1,upper=G> group_sparse_ind[N,2]; // group_id categorical variable 
  matrix[N,K] X; // design matrix, constant included
  vector[N] y; // observation
  real nu; // lkj-prior hyperparameter
}
parameters {
  row_vector[K] mu_beta;
  matrix[K,G] z;
  cholesky_factor_corr[K] L_Omega;
  vector<lower=0>[K] tau;
  real<lower=0> sigma;
}
transformed parameters {
  matrix[G,K] beta;
  beta <- rep_matrix(mu_beta,G) + (diag_pre_multiply(tau,L_Omega) * z)';
}
model {
  vector[N] mu_y;
  for(i in 1:N)
    mu_y[i] <- X[i] * beta[group_id[i]]';
  // likelihood
  y ~ normal(mu_y,sigma);

  // priors
  to_vector(z) ~ normal(0,1); // implies beta[g] ~ multi_normal(mu_beta,Sigma)
  tau ~ cauchy(0,1);
  sigma ~ cauchy(0,2.5);
  L_Omega ~ lkj_corr_cholesky(nu);
  mu_beta ~ normal(0,1);
}
generated quantities {
  matrix[K,K] cov_mat;

  cov_mat <- L_Omega * L_Omega';
}
```

However, it does compile in 2.6.0 of RStan. The following compilation errors are generated:

```
clang++ -DBOOST_RESULT_OF_USE_TR1 -DBOOST_NO_DECLTYPE -DBOOST_DISABLE_ASSERTS -I src -I stan/src -isystem stan/lib/eigen_3.2.2 -isystem stan/lib/boost_1.55.0 -Wall -pipe -DEIGEN_NO_DEBUG -Wno-unused-function -ftemplate-depth-256    -O3 -o ../test_models_hier/hier_optim src/cmdstan/main.cpp -include ../test_models_hier/hier_optim.hpp 
In file included from <built-in>:175:
In file included from <command line>:5:
In file included from ../test_models_hier/hier_optim.hpp:3:
In file included from stan/src/stan/model/model_header.hpp:35:
In file included from stan/src/stan/prob/distributions.hpp:5:
In file included from stan/src/stan/prob/distributions/multivariate.hpp:4:
In file included from stan/src/stan/prob/distributions/multivariate/continuous.hpp:15:
stan/src/stan/prob/distributions/multivariate/continuous/lkj_corr.hpp:81:37: error: use of overloaded operator '*' is ambiguous (with operand types
      'double' and 'Eigen::Matrix<var, Eigen::Dynamic, 1>')
        values += (2.0 * eta - 2.0) * log_diagonals;
                  ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~
../test_models_hier/hier_optim.hpp:327:28: note: in instantiation of function template specialization 'stan::prob::lkj_corr_cholesky_log<true,
      stan::agrad::var, double>' requested here
            lp_accum__.add(lkj_corr_cholesky_log<propto__>(L_Omega, nu));
                           ^
stan/src/stan/model/util.hpp:99:21: note: in instantiation of function template specialization
      'hier_optim_model_namespace::hier_optim_model::log_prob<true, true, stan::agrad::var>' requested here
          .template log_prob<propto,
                    ^
stan/src/stan/model/util.hpp:277:24: note: in instantiation of function template specialization 'stan::model::log_prob_grad<true, true,
      hier_optim_model_namespace::hier_optim_model>' requested here
        = stan::model::log_prob_grad<propto,
                       ^
stan/src/stan/services/command.hpp:198:28: note: in instantiation of function template specialization 'stan::model::test_gradients<true, true,
      hier_optim_model_namespace::hier_optim_model>' requested here
            = stan::model::test_gradients<true, true>
                           ^
src/cmdstan/main.cpp:7:28: note: in instantiation of function template specialization
      'stan::services::command<hier_optim_model_namespace::hier_optim_model>' requested here
    return stan::services::command<stan_model>(argc,argv);
                           ^
stan/src/stan/agrad/rev/operators/operator_multiplication.hpp:114:16: note: candidate function
    inline var operator*(const double a, const var& b) {
               ^
stan/lib/eigen_3.2.2/Eigen/src/Core/../plugins/CommonCwiseUnaryOps.h:76:1: note: candidate function
operator*(const Scalar& scalar, const StorageBaseType& matrix)
^
stan/src/stan/agrad/rev/operators/operator_multiplication.hpp:82:16: note: candidate function
    inline var operator*(const var& a, const var& b) {
               ^
In file included from <built-in>:175:
In file included from <command line>:5:
../test_models_hier/hier_optim.hpp:327:28: error: no matching function for call to 'lkj_corr_cholesky_log'
            lp_accum__.add(lkj_corr_cholesky_log<propto__>(L_Omega, nu));
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
stan/src/stan/model/util.hpp:99:21: note: in instantiation of function template specialization
      'hier_optim_model_namespace::hier_optim_model::log_prob<true, false, stan::agrad::var>' requested here
          .template log_prob<propto,
                    ^
stan/src/stan/optimization/newton.hpp:68:31: note: in instantiation of function template specialization 'stan::model::log_prob_grad<true, false,
      hier_optim_model_namespace::hier_optim_model>' requested here
            f1 = stan::model::log_prob_grad<true,false>(model,
                              ^
stan/src/stan/services/command.hpp:279:38: note: in instantiation of function template specialization
      'stan::optimization::newton_step<hier_optim_model_namespace::hier_optim_model>' requested here
            lp = stan::optimization::newton_step
                                     ^
src/cmdstan/main.cpp:7:28: note: in instantiation of function template specialization
      'stan::services::command<hier_optim_model_namespace::hier_optim_model>' requested here
    return stan::services::command<stan_model>(argc,argv);
                           ^
stan/src/stan/prob/distributions/multivariate/continuous/lkj_corr.hpp:48:5: note: candidate template ignored: substitution failure [with propto =
      true, T_covar = stan::agrad::var, T_shape = double]
    lkj_corr_cholesky_log(
    ^
stan/src/stan/prob/distributions/multivariate/continuous/lkj_corr.hpp:91:5: note: candidate template ignored: invalid explicitly-specified argument
      for template parameter 'T_covar'
    lkj_corr_cholesky_log(
    ^
2 errors generated.
make: *** [../test_models_hier/hier_optim] Error 1
```

I'm on OSX Yosemite, with the most up-to-date Xcode.

**Comment by bob-carpenter** [comment]
OK --- we definitely need to fix this.  This is the kind
of thing I kept having to fix in our test code, so it makes
me worry there are other cases that our tests didn't catch.
Not surprising it's multivariate as those have the weakest
testing.

Anyone want to help with creating test cases?

We need to fix this before we can remove C++11 dependency
unless others have a good idea of how to do it so it'll work
on both Windows and Linux, 32 and 64 bit.

- Bob

**Comment by bgoodri** [comment]
I am not understanding this bug yet, but I had var.hpp working without warnings just by putting the two long long constructors inside a conditional compilation block that tested for C++11.

**Comment by bob-carpenter** [comment]
Did you have that working *on Windows*?  The problem
is that Windows is "different"
          Win32   Win64
  int        32       32
  long       32       32
  size_t     32       64
  long long   ?       64

- Bob

**Comment by bgoodri** [comment]
I didn't test it on Windows but it was just

#if __cplusplus >= 201103L

  // define constructors inputing a possibly unsigned long long

#endif


So I can't imagine it not compiling on mingw's version of g++4.6 or Apple's
version of llvm-g++-4.2 or any other compiler that does not claim to be
C++11 compliant. I just didn't know if that was sufficient.

**Comment by bob-carpenter** [comment]
I fixed everything so it should work now.

The problem is that it's not C++11 per se that was
the issue --- we need to somehow have the size_t constructor
in play for Windows64, because long is only 32 bits there.
But if you add size_t or ptrdiff_t, it's a conflict for the
other interfaces.  So I just ifdefed the size_t and ptrdiff_t
signatures for Win64 and everything should be hunky dory.

I really don't like these varying sizes in C++.  Java was soooo
much easier with its fixed sizes.

- Bob
